package-lock.json, package.json
=> packagejson

package-lock.json, package.json, src/app.js, src/controllers/home.js, src/controllers/index.js, src/index.js
Created app.js, index.js and controllors/index.js. No error handling at the moment 
relates #13
=> Basic server now running

public/theme.css, src/views/login.hbs, src/views/send.hbs
currently focusing on mobile first design and will update for desktop if time
=> #28 adds styling to send page

package-lock.json, package.json, public/theme.css, src/views/info_page.hbs, src/views/partials/htmlHeader.hbs, src/views/send.hbs
if time could use improvement for desktop styling
=> Adds styling to info page to welcome new users

package-lock.json, src/app.js, src/controllers/login.js, src/controllers/signup.js
The path db/queries didnt work. I changed it to the path to user/queries. There are no errors now
=> debugged the app so that it runs without errors

src/index.js, src/views/signup.hbs
=> Adds styling to sign up page

public/theme.css, src/index.js, src/views/progress.hbs
* May still need editing when navbar and header styling added
=> Adds styling to progress page

src/views/signup.hbs
- removed header from the sign up hbs
- added p closing tag to sign up hbs
=> Signupheader

src/controllers/background.js, src/controllers/index.js, src/model/form_queries.js, src/views/background.hbs
Pressing ok saves background data into database and then loads the next page. 
'get'ting the background page inserts any data already in the database into the form.
=> #53 Background section saves and prepopulates from database

public/theme.css, src/index.js, src/views/about.hbs
#28 
adds style to about me page
=> add styling to about me questions

src/controllers/login.js, src/controllers/validate.js, tests/validator.test.js
Req.session.destination seemed to be causing the issue.
I also removed validation from the login form because it's weird if it tells you your password needs to be more than 8 characters when you're trying to log in.
=> #1 Fixes login

public/theme.css, src/index.js, src/views/background.hbs
=> Adds Styling to background question

src/app.js, src/index.js, src/views/about.hbs, src/views/appointments.hbs, src/views/background.hbs, src/views/home.hbs, src/views/partials/navbar.hbs, src/views/symptoms.hbs
- Fixed to page for when user scrolls 
- Added bottom margin to other hbs files to keep OK button visible
=> #28 adds styling to navbar

src/controllers/appointments.js, src/controllers/index.js, src/controllers/symptoms.js, src/model/queryGenerator.js, src/views/symptoms.hbs
#53
I changed most of the checkboxes to textareas as we don't have time to deal with questions which have checkbox options + an 'other' input
=> Saves and retrieves data in symptoms section

src/controllers/about.js, src/controllers/appointments.js, src/controllers/background.js, src/controllers/index.js, src/views/about.hbs, src/views/background.hbs
saves and retrieves about section data
=> Link about section to db

public/theme.css, src/index.js, src/views/partials/header.hbs, src/views/partials/modal.hbs
=> Adds Styling to modal

src/views/progress.hbs
=> changes edit buttons back to purple

src/controllers/appointments.js, src/controllers/symptoms.js
appointments and symptoms sections didnt load if the user didn't have any saved data for them already
=> #53 fixes bug which stopped sections from loading

src/controllers/appointments.js, src/views/appointments.hbs
before it was selected by default if the user had selected nothing
=> #75 stops no from being preselected on appointments page

src/controllers/validate.js
Changed name validator so it allows spaces but not numbers :)
=> #63 Name validator allows spaces but not numbers

src/controllers/index.js, src/controllers/info_page.js, src/controllers/signup.js, src/views/info_page.hbs
also increased the spacing of the text on the page.
Also greets user by name on welcome page (relates #29)
=> #81 redirects to welcome page on sign up

src/views/partials/header.hbs, src/views/symptoms.hbs
#75 
Needs fix on checked 'no' button on appointments page before merge
=> Resolves ok button and hidden header bugs

src/views/appointments.hbs, src/views/login.hbs, src/views/partials/header.hbs, src/views/signup.hbs
- color on login and sign up 
- trailing letters
- font sizing
=> #88 Resolves styling bugs

src/app.js, src/views/partials/messages.hbs
Current styling show green number - now will just show text
=> removes 'li' on error message because of styling

public/theme.css, src/views/partials/progress_bar.hbs
progressbar working! yay!
[x] added div tags instead of progress tags
=> Adds progressbar to all pages with styling

src/controllers/appointments.js, src/views/appointments.hbs
Fixes bug where last two questions in section dont save or prepopulate
=> Appointments bugfix

package-lock.json, src/controllers/finish.js, src/controllers/helpers.js, src/model/form_queries.js
=> bugs fixed

README.md
Redis must be installed in order to run the app locally so it's been added to the instructions
#110
=> Adds redis to readme

src/controllers/signup.js
#154 #148 wasn't returning promise, meaning the users id wasn't being added to req.session and they weren't being logged in
=> User is now logged in properly after signup

src/views/login.hbs
Two p tags spotted open in the login.hbs file
=> Close p tags

src/views/finish.hbs, src/views/reset.hbs
Fixes: 
#160 now reset page has background overlay
=> Reset page styling

README.md, public/logout.svg, public/theme.css, src/views/forgot.hbs, src/views/login.hbs, src/views/partials/header.hbs, src/views/partials/logout.hbs, src/views/progress.hbs, src/views/reset.hbs, src/views/send.hbs, src/views/signup.hbs
#159 
* Changed font colours to meet accessibility standards.
* Replaced logout icon with svg so it can change colour with theme.
* Added anchor tags and class 'icon' to themes in css file.
(branched of off #182 )
=> Improves accessibility of colour themes

src/controllers/requireLogin.js, src/views/login.hbs, tests/router.test.js
- requireLogin now redirects to login and user can see the correct endpoint
Fixes:
#150 
#175 
Also changed placeholder values for email and password for consistency with the other pages.
=> Requirelogin now redirects

public/main.css, public/theme.css, src/views/partials/html_header.hbs
Adds padding to textarea inputs. #166 
also separates out the theme related css rules from the general rules #205
=> Styling: Padding on form inputs

src/views/progress.hbs
Makes styling the same as it is for the other buttons
=> #207 fixes styling for edit button

src/views/info_page.hbs
adds mention of confidentiality to info page as per user feedback
=> #206 adds confidentiality to info page

README.md, package.json, src/model/database/db_seed.sql, tests/database.test.js
Updates readme as per #174 
- fixes issue where password wasnt in quotes
- explains how to build and seed the database
- provides template_directory environment variable
- changes password of seed user to 'password' for ease of use, and provides login details for this user in the readme
=> #174 Readme updates

README.md
#214 
- adds updated gif showing current version of app
- updates sprint 3 info
- adds ideas for sprint 4
=> Readme updates for sprint 3

src/views/partials/header.hbs, src/views/signup.hbs
=> Css oveflow tiny fix
